protected/controllers/CategoryController.php
<?php

class CategoryController extends MockController {

    const PAGING_SESSION = "currentPage";

    /**
     * Can't using COutputCache, because in this case we used complex paging session handler
     * The problem is the paging in session will be cache to, and then if the user try to back to list
     * the user will be have page that has already cache.. so bad... 
     */
    public function filters() {

//        return array(
//            array(
//                'COutputCache',
//                'duration' => 86400,
//                'requestTypes' => array('GET'),
//                'varyByParam' => array('page'),
//                'dependency' => array(
//                    'class' => 'CDbCacheDependency',
//                    'sql' => 'SELECT MAX(last_modified) FROM Category',
//                )
//            ),
//        );
    }

    public function init() {
        parent::init();
        MockApp::app()->clientScript->registerCssFile(MockApp::app()->themeManager->baseUrl .
                '/stylesheets/sample_pages/invoice.css', 'screen');
        MockApp::app()->clientScript->registerCssFile(MockApp::app()->request->baseUrl . "/css/jpaginate.css");
        MockApp::app()->clientScript->registerScriptFile(MockApp::app()->request->baseUrl . "/js/jpaginate.js");
    }

    public function actionIndex() {
        $this->render('index');
    }

    public function actionCreate() {
        $category = new Category;
        if (isset($_GET['id']))
            $category = $this->loadCategoryById($_GET['id']);

        if (isset($_POST['Category'])) {
            $category->attributes = $_POST['Category'];
            if ($category->save(true)) {
                //refreshing current page to 1
                $this->handleSessionPaging(CategoryController::PAGING_SESSION, 0);
                $this->redirect(array('index'));
            }
        }

        $this->render('form', array('category' => $category));
    }

    public function actionDelete($id) {
        if (MockApp::app()->request->isAjaxRequest) {
            $category = $this->loadCategoryById($id);
            $data['success'] = false;
            try {
                if ($category->delete()) {
                    $data['success'] = true;
                }
            } catch (CDbException $e) {
                $data['success'] = false;
            }

            echo CJSON::encode($data);
        }
    }

    public function loadCategoryById($id) {
        $category = Category::model()->findByPk($id);
        if ($category === null)
            throw new CHttpException(404, 'The requested page does not exist.');
        return $category;
    }

    public function actionList() {
        $name = '';
        $paging = $_GET['paging'];
        if (isset($_GET['name'])) {
            $name = $_GET['name'];
        }

        $data = Category::model()->getAllCategory($name, $paging);
        //Because Yii can't load data with relation 
        //We need to convert to another array for encode to json data manually
        if (MockApp::app()->request->isAjaxRequest) {
            $jsonData['categories'] = array();
            foreach ($data['categories'] as $item) {
                $temp = array();
                $temp['id'] = $item->id;
                $temp['name'] = $item->name;
                $temp['parentId'] = $item->parent_id;
                array_push($jsonData['categories'], $temp);
            }
            if ($paging) {
                $this->handleSessionPaging(CategoryController::PAGING_SESSION, $data['pages']->currentPage);
                $page['currentPage'] = $data['pages']->currentPage;
                $page['pageCount'] = $data['pages']->pageCount;
                $jsonData['pages'] = $page;
            }
            echo CJSON::encode($jsonData);
            Yii::app()->end();
        }
    }

}

protected/controllers/DashboardController.php
<?php

class DashboardController extends MockController
{
	public function actionIndex()
	{
		$this->render('index');
	}

	// Uncomment the following methods and override them if needed
	/*
	public function filters()
	{
		// return the filter configuration for this controller, e.g.:
		return array(
			'inlineFilterName',
			array(
				'class'=>'path.to.FilterClass',
				'propertyName'=>'propertyValue',
			),
		);
	}

	public function actions()
	{
		// return external action classes, e.g.:
		return array(
			'action1'=>'path.to.ActionClass',
			'action2'=>array(
				'class'=>'path.to.AnotherActionClass',
				'propertyName'=>'propertyValue',
			),
		);
	}
	*/
}

protected/controllers/ItemController.php
<?php

class ItemController extends MockController {

    const SESSION_PAGING = "currentPage";
    const SESSION_KEY_NAME = "keyName";

    public function init() {
        parent::init();
        MockApp::app()->clientScript->registerCssFile(MockApp::app()->themeManager->baseUrl .
                '/stylesheets/sample_pages/invoice.css', 'screen');
        MockApp::app()->clientScript->registerCssFile(MockApp::app()->request->baseUrl . "/css/jpaginate.css");
        MockApp::app()->clientScript->registerScriptFile(MockApp::app()->request->baseUrl . "/js/jpaginate.js");
    }

    public function actionIndex() {
        $this->render('index');
    }

    public function actionCreate() {
        $item = new Item;
        if (isset($_GET['id']))
            $item = $this->loadItemById($_GET['id']);

        if (isset($_POST['Item'])) {
            $item->attributes = $_POST['Item'];
            if ($item->save(true)) {
                //refreshing current page to 1
                $this->handleSessionPaging(ItemController::SESSION_PAGING, 0);
                $this->redirect(array('index'));
            }
        }
        $this->render('form', array('item' => $item));
    }

    public function actionDelete($id) {
        if (MockApp::app()->request->isAjaxRequest) {
            $item = $this->loadItemById($id);
            $data['success'] = false;
            try {
                if ($item->delete()) {
                    $data['success'] = true;
                }
            } catch (CDbException $e) {
                $data['success'] = false;
            }

            echo CJSON::encode($data);
        }
    }

    public function actionList() {
        $name = '';
        $paging = $_GET['paging'];
        if (isset($_GET['name'])) {
            $name = $_GET['name'];
        }

        $data = Item::model()->getAllItem($name, $paging);
        //Because Yii can't load data with relation 
        //We need to convert to another array for encode to json data manually
        if (MockApp::app()->request->isAjaxRequest) {
            $jsonData['items'] = array();
            foreach ($data['items'] as $item) {
                $temp = array();
                $temp['id'] = $item->id;
                $temp['name'] = $item->name;
                $temp['category_name'] = $item->category->name;
                array_push($jsonData['items'], $temp);
            }
            if ($paging) {
                $this->handleSessionPaging(ItemController::SESSION_PAGING, $data['pages']->currentPage);
                $page['currentPage'] = $data['pages']->currentPage;
                $page['pageCount'] = $data['pages']->pageCount;
                $jsonData['pages'] = $page;
            }
            echo CJSON::encode($jsonData);
            Yii::app()->end();
        }
    }

    private function loadItemById($id) {
        return Item::model()->findByPk($id);
    }

}

protected/views/layouts/main.php
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta name="language" content="en" />       
        <title><?php echo CHtml::encode($this->pageTitle); ?></title>
        <?php
        ?>
    </head>

    <body>
        <div id="wrapper">

            <div id="header">
                <h1><a href="<?php echo $this->createUrl('dashboard/index'); ?>">Canvas Admin</a></h1>		

                <a href="javascript:;" id="reveal-nav">
                    <span class="reveal-bar"></span>
                    <span class="reveal-bar"></span>
                    <span class="reveal-bar"></span>
                </a>
            </div> <!-- #header -->

            <div id="search">
                <form>
                    <input type="text" name="search" placeholder="Search..." id="searchField" />
                </form>		
            </div> <!-- #search -->

            <?php echo $content; ?>

        </div>

    </body>
</html>

<script>
    $(function() {
        $( "#dialog:ui-dialog" ).dialog( "destroy" );
	
        $( "#dialog-data-not-found" ).dialog({
            autoOpen : false,
            resizable: false,
            modal: true,
            buttons: {
                Ok: function() {
                    $( this ).dialog( "close" );
                }
            }
        });
    });
    
    $(function() {
        $( "#dialog:ui-dialog" ).dialog( "destroy" );
	
        $( "#dialog-delete-not-found" ).dialog({
            autoOpen : false,
            resizable: false,
            modal: true,
            buttons: {
                Ok: function() {
                    $( this ).dialog( "close" );
                }
            }
        });
    });
</script>

<!-- This dialog form for used general function -->
<div id="dialog-data-not-found" title="Information">
    <p>
        <br>
            <span class="ui-icon ui-icon-circle-check" style="float:left; margin:0 7px 50px 0;"></span>
            The data that you want can't be found !
    </p>      
</div>

<div id="dialog-delete-confirm" title="Confirmation">        
    <p>
        <br>
            <span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 50px 0;"></span>
            These items will be permanently deleted and cannot be recovered. Are you sure?
    </p>
</div>

<div id="dialog-delete-not-found" title="Information">
    <p>
        <br>
            <span class="ui-icon ui-icon-circle-check" style="float:left; margin:0 7px 50px 0;"></span>
            Please checked your data that you want delete !
    </p>      
</div>

protected/views/layouts/sidebar.php
<?php $this->beginContent('//layouts/main'); ?>

<?php //$this->beginCache(CategoryController::CACHE_SIDEBAR); ?>
<div id="sidebar">

    <ul id="mainNav">
        <li id="navDashboard" class="<?php echo MockController::cssActiveMenu(array('dashboard')); ?>">
            <span class="icon-home"></span>
            <a href="<?php echo $this->createUrl('dashboard/index'); ?>">Dashboard</a>
        </li>

        <li id="navPages" class="<?php echo MockController::cssActiveMenu(array('category', 'item', 'purchase')); ?>">
            <span class="icon-document-alt-stroke"></span>
            <a href="javascript:;">Master Data</a>

            <ul class="subNav">
                <li><a href="<?php echo $this->createUrl('category/index'); ?>">Category</a></li>
                <li><a href="<?php echo $this->createUrl('item/index'); ?>">Item</a></li>
                <li><a href="<?php echo $this->createUrl('purchase/index'); ?>">Purchase</a></li>
                <li><a href="<?php echo $this->createUrl('balance/index'); ?>">Balance</a></li>
                <li><a href="calendar.html">Calendar</a></li>
                <li><a href="stream.html">Stream</a></li>
                <li><a href="gallery.html">Gallery</a></li>
                <li><a href="reports.html">Reports</a></li>
            </ul>
        </li>

        <li id="navForms" class="nav">
            <span class="icon-article"></span>
            <a href="javascript:;">Form Elements</a>

            <ul class="subNav">
                <li><a href="forms.html">Layouts & Elements</a></li>
                <li><a href="forms-validations.html">Validations</a></li>
            </ul>
        </li>

        <li id="navType" class="nav">
            <span class="icon-info"></span>
            <a href="typography.html">Typography</a>
        </li>

        <li id="navGrid" class="nav">
            <span class="icon-layers"></span>
            <a href="grids.html">Grid Layout</a>
        </li>

        <li id="navTables" class="nav">
            <span class="icon-list"></span>
            <a href="tables.html">Tables</a>
        </li>

        <li id="navButtons" class="nav">
            <span class="icon-compass"></span>
            <a href="buttons.html">Buttons & Icons</a>
        </li>

        <li id="navInterface" class="nav">
            <span class="icon-equalizer"></span>
            <a href="interface.html">Interface Elements</a>
        </li>

        <li id="navCharts" class="nav">
            <span class="icon-chart"></span>
            <a href="charts.html">Charts & Graphs</a>
        </li>

        <li id="navMaps" class="nav">
            <span class="icon-map-pin-fill"></span>
            <a href="maps.html">Map Elements</a>
        </li>

        <li class="nav">
            <span class="icon-denied"></span>
            <a href="javascript:;">Error Pages</a>

            <ul class="subNav">
                <li><a href="error-401.html">401 Page</a></li>
                <li><a href="error-403.html">403 Page</a></li>
                <li><a href="error-404.html">404 Page</a></li>
                <li><a href="error-500.html">500 Page</a></li>
                <li><a href="error-503.html">503 Page</a></li>
            </ul>
        </li>
    </ul>

</div> <!-- #sidebar -->


<?php //$this->endCache(); ?>
<div id="content">
    <?php echo $content; ?>
</div> <!-- #content -->
<?php //$this->beginCache(CategoryController::CACHE_SIDEBAR); ?>
<div id="footer">
    Copyright &copy; 2012, MadeByAmp Themes.
</div>

<div id="topNav">
    <ul>
        <li>
            <a href="#menuProfile" class="menu">John Doe</a>

            <div id="menuProfile" class="menu-container menu-dropdown">
                <div class="menu-content">
                    <ul class="">
                        <li><a href="javascript:;">Edit Profile</a></li>
                        <li><a href="javascript:;">Edit Settings</a></li>
                        <li><a href="javascript:;">Suspend Account</a></li>
                    </ul>
                </div>
            </div>
        </li>
        <li><a href="javascript:;">Upgrade</a></li>
        <li><a href="index-2.html">Logout</a></li>
    </ul>
</div> <!-- #topNav -->

<div id="quickNav">
    <ul>
        <li class="quickNavMail">
            <a href="#menuAmpersand" class="menu"><span class="icon-book"></span></a>		



            <div id="menuAmpersand" class="menu-container quickNavConfirm">
                <div class="menu-content cf">							

                    <div class="qnc qnc_confirm">

                        <h3>Confirm</h3>

                        <div class="qnc_item">
                            <div class="qnc_content">
                                <span class="qnc_title">Confirm #1</span>
                                <span class="qnc_preview">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do.</span>
                                <span class="qnc_time">3 hours ago</span>
                            </div> <!-- .qnc_content -->

                            <div class="qnc_actions">						
                                <button class="btn btn-primary btn-small">Accept</button>
                                <button class="btn btn-quaternary btn-small">Not Now</button>
                            </div>
                        </div>

                        <div class="qnc_item">
                            <div class="qnc_content">
                                <span class="qnc_title">Confirm #2</span>
                                <span class="qnc_preview">Duis aute irure dolor in henderit in voluptate velit esse cillum dolore.</span>
                                <span class="qnc_time">3 hours ago</span>
                            </div> <!-- .qnc_content -->

                            <div class="qnc_actions">						
                                <button class="btn btn-primary btn-small">Accept</button>
                                <button class="btn btn-quaternary btn-small">Not Now</button>
                            </div>
                        </div>

                        <div class="qnc_item">
                            <div class="qnc_content">
                                <span class="qnc_title">Confirm #3</span>
                                <span class="qnc_preview">Duis aute irure dolor in henderit in voluptate velit esse cillum dolore.</span>
                                <span class="qnc_time">3 hours ago</span>
                            </div> <!-- .qnc_content -->

                            <div class="qnc_actions">						
                                <button class="btn btn-primary btn-small">Accept</button>
                                <button class="btn btn-quaternary btn-small">Not Now</button>
                            </div>
                        </div>

                        <a href="javascript:;" class="qnc_more">View all Confirmations</a>

                    </div> <!-- .qnc -->	
                </div>
            </div>
        </li>
        <li class="quickNavNotification">
            <a href="#menuPie" class="menu"><span class="icon-chat"></span></a>

            <div id="menuPie" class="menu-container">
                <div class="menu-content cf">					

                    <div class="qnc">

                        <h3>Notifications</h3>

                        <a href="javascript:;" class="qnc_item">
                            <div class="qnc_content">
                                <span class="qnc_title">Notification #1</span>
                                <span class="qnc_preview">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do.</span>
                                <span class="qnc_time">3 hours ago</span>
                            </div> <!-- .qnc_content -->
                        </a>

                        <a href="javascript:;" class="qnc_item">
                            <div class="qnc_content">
                                <span class="qnc_title">Notification #2</span>
                                <span class="qnc_preview">Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu.</span>
                                <span class="qnc_time">3 hours ago</span>
                            </div> <!-- .qnc_content -->
                        </a>

                        <a href="javascript:;" class="qnc_more">View all Confirmations</a>

                    </div> <!-- .qnc -->
                </div>
            </div>				
        </li>
    </ul>		
</div> <!-- .quickNav -->

<?php //$this->endCache(); ?>
<?php $this->endContent(); ?>