protected/models/Item.php
<?php

/**
 * This is the model class for table "Item".
 *
 * The followings are the available columns in table 'Item':
 * @property integer $id
 * @property string $name 
 * @property string $lastModified
 * @property integer $category_id
 *
 * The followings are the available model relations:
 * @property Category $category
 * @property Purchase[] $purchases
 */
class Item extends CActiveRecord {

    const PAGE_SIZE = 9;

    /**
     * Returns the static model of the specified AR class.
     * @param string $className active record class name.
     * @return Item the static model class
     */
    public static function model($className = __CLASS__) {
        return parent::model($className);
    }

    public function behaviors() {
        return array(
            'CTimestampBehavior' => array(
                'class' => 'zii.behaviors.CTimestampBehavior',
                'createAttribute' => 'created_date',
                'updateAttribute' => 'modified_date',
            )
        );
    }

    protected function afterConstruct() {
        //Set default value to view. Yii alwasy set empty value as 0
        //I don't know how to fix this yet
        if (!isset($this->id)) {
            $this->name = "";
            $this->category_id = "";
            $this->category = new Category;
        }
    }

    /**
     * @return string the associated database table name
     */
    public function tableName() {
        return 'item';
    }

    /**
     * @return array validation rules for model attributes.
     */
    public function rules() {
        // NOTE: you should only define rules for those attributes that
        // will receive user inputs.
        return array(
            array('name', 'required', 'message' => 'Please enter a value for {attribute}.'),
            array('name', 'length', 'max' => 255),
            array('category_id', 'required', 'message' => 'Please enter a value for {attribute}.'),
            array('category_id', 'numerical', 'integerOnly' => true, 'message' => 'Please enter a value for {attribute}.'),
            array('last_modified', 'safe'),
        );
    }

    /**
     * @return array relational rules.
     */
    public function relations() {
        // NOTE: you may need to adjust the relation name and the related
        // class name for the relations automatically generated below.
        return array(
            'category' => array(self::BELONGS_TO, 'category', 'category_id', 'joinType' => 'INNER JOIN'),
            'purchases' => array(self::HAS_MANY, 'purchase', 'item_id'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
            'id' => 'ID',
            'name' => 'Name',
            'last_modified' => 'Last Modified',
            'category_id' => 'Category',
        );
    }

    public function getAllItem($name, $paging) {
        $data = array();
        $criteria = new CDbCriteria();
        $criteria->alias = 'i';
        if (isset($name)) {
            $criteria->condition = "i.name LIKE '%" . $name . "%'";
        }
        $criteria->order = "i.id DESC";

        if ($paging) {
            $count = Item::model()->count($criteria);
            $pages = new CPagination($count);
            $pages->pageSize = Item::PAGE_SIZE;
            $pages->validateCurrentPage = true;
            $pages->applyLimit($criteria);
            $data['pages'] = $pages;
        }

        $data['items'] = Item::model()->with('category')->findAll($criteria);
        return $data;
    }

}

protected/controllers/ItemController.php
<?php

class ItemController extends MockController {

    const SESSION_PAGING = "currentPage";
    const SESSION_KEY_NAME = "keyName";

    public function init() {
        parent::init();
        MockApp::app()->clientScript->registerCssFile(MockApp::app()->themeManager->baseUrl .
                '/stylesheets/sample_pages/invoice.css', 'screen');
        MockApp::app()->clientScript->registerCssFile(MockApp::app()->request->baseUrl . "/css/jpaginate.css");
        MockApp::app()->clientScript->registerScriptFile(MockApp::app()->request->baseUrl . "/js/jpaginate.js");
    }

    public function actionIndex() {
        $this->render('index');
    }

    public function actionCreate() {
        $item = new Item;
        if (isset($_GET['id']))
            $item = $this->loadItemById($_GET['id']);

        if (isset($_POST['Item'])) {
            $item->attributes = $_POST['Item'];
            if ($item->save(true)) {
                //refreshing current page to 1
                $this->handleSessionPaging(ItemController::SESSION_PAGING, 0);
                $this->redirect(array('index'));
            }
        }
        $this->render('form', array('item' => $item));
    }

    public function actionDelete($id) {
        if (MockApp::app()->request->isAjaxRequest) {
            $item = $this->loadItemById($id);
            $data['success'] = false;
            try {
                if ($item->delete()) {
                    $data['success'] = true;
                }
            } catch (CDbException $e) {
                $data['success'] = false;
            }

            echo CJSON::encode($data);
        }
    }

    public function actionList() {
        $name = '';
        $paging = $_GET['paging'];
        if (isset($_GET['name'])) {
            $name = $_GET['name'];
        }

        $data = Item::model()->getAllItem($name, $paging);
        //Because Yii can't load data with relation 
        //We need to convert to another array for encode to json data manually
        if (MockApp::app()->request->isAjaxRequest) {
            $jsonData['items'] = array();
            foreach ($data['items'] as $item) {
                $temp = array();
                $temp['id'] = $item->id;
                $temp['name'] = $item->name;
                $temp['category_name'] = $item->category->name;
                array_push($jsonData['items'], $temp);
            }
            if ($paging) {
                $this->handleSessionPaging(ItemController::SESSION_PAGING, $data['pages']->currentPage);
                $page['currentPage'] = $data['pages']->currentPage;
                $page['pageCount'] = $data['pages']->pageCount;
                $jsonData['pages'] = $page;
            }
            echo CJSON::encode($jsonData);
            Yii::app()->end();
        }
    }

    private function loadItemById($id) {
        return Item::model()->findByPk($id);
    }

}

protected/views/item/form.php
<div id="contentHeader">
    <h1>Item</h1>
</div> <!-- #contentHeader -->
<script type="text/javascript">     
   
    $(document).ready(function(){      
        
        function fillTableItems(data){
            $('#loader').show();
            $('.table.table-striped').children('tbody').empty();
            
            $.each(data['categories'], function(i ,category){         
                var link = '<a href=javascript:; class=choose value='+category.id+'>'+category.name+'</a>'
                $('.table.table-striped').children('tbody').
                    append('<tr><td>'+link+'</td></tr>');                
            })  
           
            $('#loader').hide();
        }        
       
    
        function searchCategory(){
            $.ajax({
                url         : '<?php echo $this->createUrl("category/list/"); ?>',
                data        : {name : $("#key-name").val(), paging : 0},
                dataType    : 'json',
                type        : 'get'               
            }).done(function(data){               
                if(data['categories'].length == 0){
                    $("#dialog-data-not-found").dialog("open");                   
                }else{                   
                    fillTableItems(data);          
                }             
            });         
        }
        
        $(function() {
            $( "#dialog:ui-dialog" ).dialog( "destroy" );
		
            $( "#search-result" ).dialog({
                autoOpen: false,
                height: 480,
                resizable: false,
                width: 650,
                modal: true       
            });
        });           
        
        $(function() {
            $( "#dialog:ui-dialog" ).dialog( "destroy" );
	
            $( "#dialog-delete-confirm" ).dialog({
                autoOpen : false,
                resizable: false,
                height:190,
                width: 350,
                modal: true,
                buttons: {
                    "Delete ": function() {
                        $.ajax({
                            url         : '<?php echo $this->createUrl("item/delete"); ?>',
                            data        : {id : $("#item-id").val()},
                            dataType    : 'json',
                            type        : 'get'                            
                        }).done(function(msg){
                            if(msg['success']){
                                alert(msg['success']);  
                                $(location).attr('href', '<?php echo $this->createUrl('item/index'); ?>');      
                            }else{
                                alert("Failed");
                            }
                        });                           
                       
                        $( this ).dialog( "close" );
                    },
                    Cancel: function() {
                        $( this ).dialog( "close" );
                    }                    
                }
            });
        });
       
        $( ".table.table-striped" ).on('click','.choose',function() {
            //Save val from td content and show it to search field 
            var result =$(this).html().split("::");           
            $("#category-name").val(result[result.length-1].replace(/^ +/,""));    
            //set catgory id to hidden value
            $("#category-id").val($(this).attr('value'));            
            $("#search-result" ).dialog( "close" );
            
        });
        
        $("#back-item").button().click(function(){          
            $(location).attr('href', '<?php echo $this->createUrl('item/index'); ?>'); 
        });
        
        $("#delete-item").button().click(function(){
            $("#dialog-delete-confirm").dialog("open");
        });
        
        $("#save-item").button().click(function(){
            $(location).attr('href', '<?php echo $this->createUrl('item/index'); ?>'); 
        });
        
        $( "#search-category" ).button().click(function() {           
            searchCategory();
            $( "#search-result" ).dialog( "open" );
        });
        
        $("#key-name").change(function(){
            searchCategory();
        });
            
    });         
       
</script>
<div class="container">    
    <?php
    $form = $this->beginWidget('CActiveForm', array(
        'id' => 'item-form',
        'enableAjaxValidation' => FALSE,
            ));
    ?>
    <?php echo $form->hiddenField($item, 'id', array('id' => 'item-id')); ?>
    <div class = "grid-24">
        <div class = "box plain">
            <div class = "dataTables_filter">
                <button type="submit" class = "btn btn-quaternary" id = "save-item">
                    <span class = "icon-document-alt-stroke"></span>
                    Save
                </button>
                <button type="button" class = "btn btn-quaternary" id = "delete-item">
                    <span class = "icon-x-alt"></span>
                    Delete
                </button>
                <button type="button" class = "btn btn-quaternary" id = "back-item">
                    <span class = "icon-curved-arrow"></span>
                    Back
                </button>
            </div>          
        </div><!-- box -->  
        </br>
        <div class="widget">
            <div class="widget-content">
                <div class="field-group">
                    <?php //var_dump($item);   ?>
                    <div class="field">
                        <?php echo $form->labelEx($item, 'name'); ?>
                    </div>
                    <div class="field">
                        <?php
                        echo $form->textField($item, 'name', array(
                            'size' => 70,
                            'maxlength' => 255,
                            'class' => 'validate[required]'
                        ));
                        ?>
                    </div>
                    <div class="field">
                        <?php echo $form->error($item, 'name'); ?>
                    </div>
                </div>            
                <div class="field-group"> 
                    <?php echo $form->hiddenField($item, 'category_id', array('id' => 'category-id')); ?>
                    <div class="field">
                        <?php echo $form->labelEx($item, 'category_id'); ?>
                    </div>
                    <div class="field">
                        <?php
                        echo $form->textField($item->category, 'name', array(
                            'id' => 'category-name',
                            'size' => 70, 'maxlength' => 255,
                            'class' => 'validate[required]',
                            'disabled' => 'true',
                        ));
                        ?>
                        <button type="button" class="btn btn-small btn-quaternary" id="search-category">
                            <span class="icon-magnifying-glass">Search</span>
                        </button>
                    </div>
                    <div class="field">
                        <?php echo $form->error($item, 'category_id'); ?>
                    </div>
                </div> <!-- .field-group -->
                <?php $this->endWidget(); ?>
            </div> <!--.grid-->
        </div><!-- widget -->
    </div><!-- widget content -->
</div> <!--.container-->

<div id = "search-result" title = "Search Result">
    <span><br></span>
    Search : 
    <input type="text" id="key-name"/>
    <table class = "table table-striped">
        <thead>
            <tr>
                <th style = "width: 50%">Category Name</th>                    
            </tr>
        </thead>
        <tbody>

        </tbody>
    </table>

</div>






protected/views/item/index.php
<script type="text/javascript">     
   
    $(document).ready(function(){               
       
        init();
        
        function init(){            
            $.ajax({
                url         : '<?php echo $this->createUrl("item/list/page");echo '/' . MockApp::app()->session[ItemController::SESSION_PAGING]?>',
                dataType    : 'json' ,    
                data        : {paging : 1}
            }).done(function(data){  
                currentPage = data['pages'].currentPage;
                pageCount = data['pages'].pageCount;                
                fillTableItems(data, pageCount, currentPage);               
            });
        }        
               
        function fillTableItems(data,pageCount,currentPage){
            $('#loader').show();
            $('.table.table-striped').children('tbody').empty();
            
            $.each(data['items'], function(i ,item){         
                if(pageCount != null){
                    paginate(pageCount, currentPage);
                }
                var linkDetail = '<a href=javascript:; value='+item.id+' class=edit><span>&nbsp;&nbsp;&nbsp;&nbsp;</span></a>';                   
                $('.table.table-striped').children('tbody').
                    append('<tr><td>'+item.name+'</td><td>'+item.category_name+'</td><td>'+linkDetail+'</td></tr>');                
            })  
           
            $('#loader').hide();
        }
        
        function paginate(pageCount, currentPage) {
            
            $("#paginate").paginate({
                count                       : pageCount,
                start                       : currentPage +1 ,           
                display                     : 10,
                border                      : false,
                text_color                  : '#79B5E3',
                background_color            : 'none',	
                text_hover_color            : '#2573AF',
                background_hover_color      : 'none', 
                images                      : false,
                mouse                       : 'press',
                onChange                    : function(page){                     
                    $.ajax({
                        url         : '<?php echo $this->createUrl("item/list/page"); ?>/'+page,
                        data        : {name : $('#search-name').val(), paging : 1},
                        dataType    : 'json',
                        type        : 'get'
                    }).done(function(data){                       
                        fillTableItems(data, null, null);   
                        return false;
                    });
                }
            });
        }
        
        $(function() {
            $( "#dialog:ui-dialog" ).dialog( "destroy" );
		
            $( "#search-form" ).dialog({
                autoOpen    : false,
                height      : 180,
                resizable   : false,
                width       : 350,
                modal       : true,
                buttons     : {
                    "Search": function() {                             
                        $.ajax({
                            url         : '<?php echo $this->createUrl("item/list/"); ?>',
                            data        : {name : $("#search-name").val(), paging : 0},
                            dataType    : 'json',
                            type        : 'get'               
                        }).done(function(data){     
                            if(data['items'].length ==0 ){
                                $( "#dialog-data-not-found" ).dialog("open");                                  
                            }else{
                                fillTableItems(data, pageCount, currentPage); 
                                $('#paginate').hide();    
                                $('#search-result').html(data['items'].length+" records found in database");
                            }                   
                        });
                        
                        $( this ).dialog( "close" );                        
                    }        
                }
            });
        });           
      
        $( "#search-item" ).button().click(function() {
            $( "#search-form" ).dialog( "open" );
        });
        
        $( ".table.table-striped" ).on('click','.edit',function() {
            $(location).attr('href', '<?php echo $this->createUrl('item/create'); ?>/id/'+$(this).attr('value'));           
        });       
        
        $("#add-item").button().click(function(){            
            $(location).attr('href', '<?php echo $this->createUrl('item/create'); ?>'); 
        });            
    });    
        
</script>
<div id="contentHeader">
    <h1>Item</h1>
</div> <!-- #contentHeader -->

<div class="container"> 
    <div id = "loader" style = 'display:none'>
        <img src = "<?php echo MockApp::app()->themeManager->baseUrl . '/images/loaders/big-roller.gif'; ?>" />
    </div>
    <div class = "grid-24">
        <div class = "box plain">
            <div class = "dataTables_filter">
                <button class = "btn btn-quaternary" id = "add-item">
                    <span class = "icon-move-alt2"></span>
                    New Data
                </button>
                <button class = "btn btn-quaternary" id = "search-item">
                    <span class = "icon-magnifying-glass"></span>
                    Search
                </button>
            </div>
        </div>
        <div id = "paginate" class = "jPaginate">
            <div class = "jPag-control-back">
                <a class = "jPag-first" style = "color: rgb(121, 181, 227); ">First</a>
                <span class = "jPag-sprevious">«</span>
            </div>
            <div class = "jPag-control-front" style = "left: 399px; ">
                <span class = "jPag-snext">»</span>
                <a class = "jPag-last" style = "color: rgb(121, 181, 227); ">Last</a>
            </div>
        </div>
        <div id="search-result">
           
        </div>
        <table class = "table table-striped">
            <thead>
                <tr>
                    <th style = "width: 50%">Item Name</th>
                    <th style = "width: 43%">Category Name</th>
                    <th style = "width: 7%" ></th>
                </tr>
            </thead>
            <tbody>

            </tbody>
        </table>
    </div> <!--.grid-->
</div> <!--.container-->


<div id = "search-form" title = "Search Item">
    <span><br></span>
    <label for = "name">Item Name</label>
    <input type = "text" name = "name"  size="40" id = "search-name" class = "text ui-widget-content ui-corner-all" />
</div>