protected/models/Category.php
<?php

/**
 * This is the model class for table "category".
 *
 * The followings are the available columns in table 'category':
 * @property integer $id
 * @property string $name
 * @property datetime $last_modified
 * @property integer $sort_order
 * @property integer $parent_id
 *
 * The followings are the available model relations:
 * @property Item[] $items
 */
class Category extends CActiveRecord {

    const PAGE_SIZE = 9;

    /**
     * Returns the static model of the specified AR class.
     * @param string $className active record class name.
     * @return Category the static model class
     */
    public static function model($className = __CLASS__) {
        return parent::model($className);
    }

    /**
     * @return string the associated database table name
     */
    public function tableName() {
        return 'category';
    }

    protected function afterConstruct() {
        if (!isset($this->id)) {
            $this->name = "";
        }
    }

    /**
     * @return array validation rules for model attributes.
     */
    public function rules() {
        // NOTE: you should only define rules for those attributes that
        // will receive user inputs.
        return array(
            array('parent_id', 'required'),
            array('sort_order, parent_id', 'numerical', 'integerOnly' => true),
            array('name', 'length', 'max' => 255),
            array('name', 'required', 'message' => 'Please enter a value for {attribute}.'),
            // The following rule is used by search().
            // Please remove those attributes that should not be searched.
            array('id, name, sort_order, parent_id', 'safe', 'on' => 'search'),
        );
    }

    /**
     * @return array relational rules.
     */
    public function relations() {
        // NOTE: you may need to adjust the relation name and the related
        // class name for the relations automatically generated below.
        return array(
            'items' => array(self::HAS_MANY, 'item', 'category_id'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
            'id' => 'ID',
            'name' => 'Name',
            'sort_order' => 'Sort Order',
            'parent_id' => 'Parent',
            'last_modified' => 'Last Modified'
        );
    }

    /**
     * This recursif function
     * Check whether categery has parent it self.
     * @param type $category
     * @return type String 
     */
    public function hasParent($category) {
        if ($category->parent_id != 0) {
            $parent = Category::model()->find('id=:id', array(':id' => $category->parent_id));
            return $this->hasParent($parent) . ' :: ' . $category->name;
        } else {
            return $category->name;
        }
    }

    public function getAllCategory($name = null, $paging = true) {
        $data = array();
        $criteria = new CDbCriteria();
        $criteria->alias = 'c';
        if (isset($name)) {
            $criteria->condition = "c.name LIKE '%" . $name . "%'";
        }
        $criteria->order = "c.id DESC";

        if ($paging) {
            $count = Category::model()->count($criteria);
            $pages = new CPagination($count);
            $pages->pageSize = Category::PAGE_SIZE;
            $pages->validateCurrentPage = true;
            $pages->applyLimit($criteria);
            $data['pages'] = $pages;
        }

        //$dependency = new CDbCacheDependency('SELECT MAX(last_modified) FROM Category');
        $data['categories'] = Category::model()->getAllCategoriesWithParent($criteria);
        return $data;
    }

    /**
     * Get all categories with parent
     * @param type int $index 
     * @param type int $pageSize
     * @return type array
     */
    public function getAllCategoriesWithParent($criteria = null) {
        $result = array();
        $categories = Category::model()->findAll($criteria);
        foreach ($categories as $category) {
            $category->name = Category::model()->hasParent($category);
            $result [] = $category;
        }
        return $result;
    }

    /**
     * Used to combobox component to select default category and select it as default
     * @return int(Selected Category)
     */
    public function getSelectedCategory() {
        if (isset($this->parent_id))
            return $this->parent_id;
        return 1;
    }

    public function getOptions() {
        return CHtml::listData($this->getAllCategoriesWithParent(), 'id', 'name');
    }

}

protected/controllers/CategoryController.php
<?php

class CategoryController extends MockController {

    const PAGING_SESSION = "currentPage";

    /**
     * Can't using COutputCache, because in this case we used complex paging session handler
     * The problem is the paging in session will be cache to, and then if the user try to back to list
     * the user will be have page that has already cache.. so bad... 
     */
    public function filters() {

//        return array(
//            array(
//                'COutputCache',
//                'duration' => 86400,
//                'requestTypes' => array('GET'),
//                'varyByParam' => array('page'),
//                'dependency' => array(
//                    'class' => 'CDbCacheDependency',
//                    'sql' => 'SELECT MAX(last_modified) FROM Category',
//                )
//            ),
//        );
    }

    public function init() {
        parent::init();
        MockApp::app()->clientScript->registerCssFile(MockApp::app()->themeManager->baseUrl .
                '/stylesheets/sample_pages/invoice.css', 'screen');
        MockApp::app()->clientScript->registerCssFile(MockApp::app()->request->baseUrl . "/css/jpaginate.css");
        MockApp::app()->clientScript->registerScriptFile(MockApp::app()->request->baseUrl . "/js/jpaginate.js");
    }

    public function actionIndex() {
        $this->render('index');
    }

    public function actionCreate() {
        $category = new Category;
        if (isset($_GET['id']))
            $category = $this->loadCategoryById($_GET['id']);

        if (isset($_POST['Category'])) {
            $category->attributes = $_POST['Category'];
            if ($category->save(true)) {
                //refreshing current page to 1
                $this->handleSessionPaging(CategoryController::PAGING_SESSION, 0);
                $this->redirect(array('index'));
            }
        }

        $this->render('form', array('category' => $category));
    }

    public function actionDelete($id) {
        if (MockApp::app()->request->isAjaxRequest) {
            $category = $this->loadCategoryById($id);
            $data['success'] = false;
            try {
                if ($category->delete()) {
                    $data['success'] = true;
                }
            } catch (CDbException $e) {
                $data['success'] = false;
            }

            echo CJSON::encode($data);
        }
    }

    public function loadCategoryById($id) {
        $category = Category::model()->findByPk($id);
        if ($category === null)
            throw new CHttpException(404, 'The requested page does not exist.');
        return $category;
    }

    public function actionList() {
        $name = '';
        $paging = $_GET['paging'];
        if (isset($_GET['name'])) {
            $name = $_GET['name'];
        }

        $data = Category::model()->getAllCategory($name, $paging);
        //Because Yii can't load data with relation 
        //We need to convert to another array for encode to json data manually
        if (MockApp::app()->request->isAjaxRequest) {
            $jsonData['categories'] = array();
            foreach ($data['categories'] as $item) {
                $temp = array();
                $temp['id'] = $item->id;
                $temp['name'] = $item->name;
                $temp['parentId'] = $item->parent_id;
                array_push($jsonData['categories'], $temp);
            }
            if ($paging) {
                $this->handleSessionPaging(CategoryController::PAGING_SESSION, $data['pages']->currentPage);
                $page['currentPage'] = $data['pages']->currentPage;
                $page['pageCount'] = $data['pages']->pageCount;
                $jsonData['pages'] = $page;
            }
            echo CJSON::encode($jsonData);
            Yii::app()->end();
        }
    }

}

protected/views/category/form.php
<div id="contentHeader">
    <h1>Item</h1>
</div> <!-- #contentHeader -->
<script type="text/javascript">     
   
    $(document).ready(function(){         
                 
        $(function() {
            $( "#dialog:ui-dialog" ).dialog( "destroy" );
	
            $( "#dialog-delete-confirm" ).dialog({
                autoOpen : false,
                resizable: false,
                height:190,
                width: 350,
                modal: true,
                buttons: {
                    "Delete ": function() {
                        $.ajax({
                            url         : '<?php echo $this->createUrl("category/delete"); ?>',
                            data        : {id : $("#category-id").val()},
                            dataType    : 'json',
                            type        : 'get'                            
                        }).done(function(msg){
                            if(msg['success']){
                                alert(msg['success']);  
                                $(location).attr('href', '<?php echo $this->createUrl('category/index'); ?>');      
                            }else{
                                alert("Failed");
                            }
                        });                           
                       
                        $( this ).dialog( "close" );
                    },
                    Cancel: function() {
                        $( this ).dialog( "close" );
                    }                    
                }
            });
        });
       
        $( ".table.table-striped" ).on('click','.choose',function() {
            $("#search-result" ).dialog( "close" );            
        });
        
        $("#back-item").button().click(function(){          
            $(location).attr('href', '<?php echo $this->createUrl('category/index'); ?>'); 
        });
        
        $("#delete-item").button().click(function(){
            $("#dialog-delete-confirm").dialog("open");
        });
        
        $("#save-item").button().click(function(){
            $(location).attr('href', '<?php echo $this->createUrl('category/index'); ?>'); 
        });
        
        $( "#search-category" ).button().click(function() {           
            searchCategory();
            $( "#search-result" ).dialog( "open" );
        });
        
        $("#key-name").change(function(){
            searchCategory();
        });
            
    });         
       
</script>
<div class="container">    
    <?php
    $form = $this->beginWidget('CActiveForm', array(
        'id' => 'category-form',
        'enableAjaxValidation' => FALSE,
            ));
    ?>
    <?php echo $form->hiddenField($category, 'id', array('id' => 'category-id')); ?>
    <div class = "grid-24">
        <div class = "box plain">
            <div class = "dataTables_filter">
                <button type="submit" class = "btn btn-quaternary" id = "save-item">
                    <span class = "icon-document-alt-stroke"></span>
                    Save
                </button>
                <button type="button" class = "btn btn-quaternary" id = "delete-item">
                    <span class = "icon-x-alt"></span>
                    Delete
                </button>
                <button type="button" class = "btn btn-quaternary" id = "back-item">
                    <span class = "icon-curved-arrow"></span>
                    Back
                </button>
            </div>          
        </div><!-- box -->  
        </br>
        <div class="widget">
            <div class="widget-content">
                <div class="field-group">
                    <?php //var_dump($item);   ?>
                    <div class="field">
                        <?php echo $form->labelEx($category, 'name'); ?>
                    </div>
                    <div class="field">
                        <?php
                        echo $form->textField($category, 'name', array(
                            'size' => 70,
                            'maxlength' => 255,
                            'class' => 'validate[required]'
                        ));
                        ?>
                    </div>
                    <div class="field">
                        <?php echo $form->error($category, 'name'); ?>
                    </div>                   
                </div>     
                <div class="field-group">
                    <?php //var_dump($item);   ?>
                    <div class="field">
                        <?php echo $form->labelEx($category, 'parent_id'); ?>
                    </div>
                    <div class="field">
                        <?php
                        echo $form->dropDownList($category, 'parent_id', $category->getOptions());
                        ?>
                    </div>
                    <div class="field">
                        <?php echo $form->error($category, 'parent_id'); ?>
                    </div>                   
                </div>     
                <?php $this->endWidget(); ?>
            </div> <!--.grid-->
        </div><!-- widget -->
    </div><!-- widget content -->
</div> <!--.container-->

<div id = "search-result" title = "Search Result">
    <span><br></span>
    Search : 
    <input type="text" id="key-name"/>
    <table class = "table table-striped">
        <thead>
            <tr>
                <th style = "width: 50%">Category Name</th>                    
            </tr>
        </thead>
        <tbody>

        </tbody>
    </table>

</div>

protected/views/category/index.php
<script type="text/javascript">     
   
    $(document).ready(function(){               
       
        init();
        
        function init(){            
            $.ajax({
                url         : '<?php echo $this->createUrl("category/list/page");echo '/' . MockApp::app()->session[CategoryController::PAGING_SESSION] ?>',
                dataType    : 'json' ,    
                data        : {paging : 1}
            }).done(function(data){  
                currentPage = data['pages'].currentPage;
                pageCount = data['pages'].pageCount;                
                fillTableCategory(data, pageCount, currentPage);               
            });
        }        
               
        function fillTableCategory(data,pageCount,currentPage){
            $('#loader').show();
            $('.table.table-striped').children('tbody').empty();
            
            $.each(data['categories'], function(i ,category){         
                if(pageCount != null){
                    paginate(pageCount, currentPage);
                }
                var linkDetail = '<a href=javascript:; value='+category.id+' class=edit><span>&nbsp;&nbsp;&nbsp;&nbsp;</span></a>';                   
                $('.table.table-striped').children('tbody').
                    append('<tr><td>'+category.name+'</td><td>'+category.parentId+'</td><td>'+linkDetail+'</td></tr>');                
            })  
           
            $('#loader').hide();
        }
        
        function paginate(pageCount, currentPage) {
            
            $("#paginate").paginate({
                count                       : pageCount,
                start                       : currentPage +1 ,           
                display                     : 10,
                border                      : false,
                text_color                  : '#79B5E3',
                background_color            : 'none',	
                text_hover_color            : '#2573AF',
                background_hover_color      : 'none', 
                images                      : false,
                mouse                       : 'press',
                onChange                    : function(page){                     
                    $.ajax({
                        url         : '<?php echo $this->createUrl("category/list/page"); ?>/'+page,
                        data        : {name : $('#search-name').val(), paging : 1},
                        dataType    : 'json',
                        type        : 'get'
                    }).done(function(data){                       
                        fillTableCategory(data, null, null);   
                        return false;
                    });
                }
            });
        }
        
        $(function() {
            $( "#dialog:ui-dialog" ).dialog( "destroy" );
		
            $( "#search-form" ).dialog({
                autoOpen    : false,
                height      : 180,
                resizable   : false,
                width       : 350,
                modal       : true,
                buttons     : {
                    "Search": function() {                             
                        $.ajax({
                            url         : '<?php echo $this->createUrl("category/list/"); ?>',
                            data        : {name : $("#search-name").val(), paging : 0},
                            dataType    : 'json',
                            type        : 'get'               
                        }).done(function(data){               
                            if(data['categories'].length ==0 ){
                                $( "#dialog-data-not-found" ).dialog("open");                                  
                            }else{
                                fillTableCategory(data, pageCount, currentPage); 
                                $('#paginate').hide();    
                                $('#search-result').html(data['categories'].length+" records found in database");
                            }        
                        });
                        
                        $( this ).dialog( "close" );                        
                    }                 
                }
            });
        });           
      
        
        $( "#search-item" ).button().click(function() {
            $( "#search-form" ).dialog( "open" );
        });
        
        $( ".table.table-striped" ).on('click','.edit',function() {
            $(location).attr('href', '<?php echo $this->createUrl('category/create'); ?>/id/'+$(this).attr('value'));           
        });       
        
        $("#add-item").button().click(function(){            
            $(location).attr('href', '<?php echo $this->createUrl('category/create'); ?>'); 
        });            
    });    
        
</script>
<div id="contentHeader">
    <h1>Item</h1>
</div> <!-- #contentHeader -->

<div class="container"> 
    <div id = "loader" style = 'display:none'>
        <img src = "<?php echo MockApp::app()->themeManager->baseUrl . '/images/loaders/big-roller.gif'; ?>" />
    </div>
    <div class = "grid-24">
        <div class = "box plain">
            <div class = "dataTables_filter">
                <button class = "btn btn-quaternary" id = "add-item">
                    <span class = "icon-move-alt2"></span>
                    New Data
                </button>
                <button class = "btn btn-quaternary" id = "search-item">
                    <span class = "icon-magnifying-glass"></span>
                    Search
                </button>
            </div>
        </div>
        <div id = "paginate" class = "jPaginate">
            <div class = "jPag-control-back">
                <a class = "jPag-first" style = "color: rgb(121, 181, 227); ">First</a>
                <span class = "jPag-sprevious">«</span>
            </div>
            <div class = "jPag-control-front" style = "left: 399px; ">
                <span class = "jPag-snext">»</span>
                <a class = "jPag-last" style = "color: rgb(121, 181, 227); ">Last</a>
            </div>
        </div>
        <div id="search-result">
           
        </div>
        <table class = "table table-striped">
            <thead>
                <tr>
                    <th style = "width: 50%">Category Name</th>
                    <th style = "width: 43%">Parent Id</th>
                    <th style = "width: 7%" ></th>
                </tr>
            </thead>
            <tbody>

            </tbody>
        </table>
    </div> <!--.grid-->
</div> <!--.container-->


<div id = "search-form" title = "Search Category">
    <span><br></span>
    <label for = "name">Category Name</label>
    <input type = "text" name = "name"  size="40" id = "search-name" class = "text ui-widget-content ui-corner-all" />
</div>